"""
Analyze SBOM input using SBOMAI Engine.
"""

import json
from datetime import datetime
from pprint import pprint

from sbomai_ai.models.threat_intelligence import ThreatContextEmbedding
from sbomai_ai.models.threat_patterns import ExploitPatternDetector, VulnerabilityCorrelation
from sbomai_ai.models.exploit_prediction import ExploitPredictor
from sbomai_ai.models.gnn_risk_propagation import DependencyGNN

# Test SBOM input
test_sbom = {
    "components": [
        {
            "name": "log4j-core",
            "version": "2.14.1",
            "purl": "pkg:maven/org.apache.logging.log4j/log4j-core@2.14.1",
            "hashes": ["sha256:abcd1234..."],
            "licenses": ["Apache-2.0"]
        },
        {
            "name": "guava",
            "version": "30.0-jre",
            "purl": "pkg:maven/com.google.guava/guava@30.0-jre",
            "hashes": ["sha256:xyz9876..."],
            "licenses": ["Apache-2.0"]
        }
    ],
    "metadata": {
        "timestamp": "2025-07-29T12:00:00Z",
        "tool": "cyclonedx"
    }
}

def analyze_sbom(sbom_data):
    """Run comprehensive SBOM analysis"""
    print("\n=== SBOMAI Engine Analysis ===")
    print(f"Analyzing SBOM generated by {sbom_data['metadata']['tool']}")
    print(f"Timestamp: {sbom_data['metadata']['timestamp']}")
    
    # Initialize analyzers
    threat_analyzer = ThreatContextEmbedding()
    pattern_detector = ExploitPatternDetector()
    exploit_predictor = ExploitPredictor()
    
    results = {
        'components': [],
        'overall_risk_score': 0.0,
        'critical_components': [],
        'security_recommendations': []
    }
    
    # Analyze each component
    for component in sbom_data['components']:
        print(f"\n--- Analyzing {component['name']} {component['version']} ---")
        
        # 1. Threat Context Analysis
        component_data = enrich_component_data(component)
        threat_context = threat_analyzer.embed_component(component_data)
        
        # 2. Pattern Detection
        patterns = pattern_detector.analyze_component(component_data)
        
        # 3. Exploit Prediction
        exploit_prediction = exploit_predictor.predict_exploit_likelihood(
            component_data['vulnerability_data']
        )
        
        # Combine results
        component_analysis = {
            'name': component['name'],
            'version': component['version'],
            'purl': component['purl'],
            'threat_analysis': {
                'risk_score': threat_context['risk_score'],
                'detected_patterns': patterns['pattern_matches'],
                'exploit_probability': exploit_prediction['exploit_probability'],
                'vulnerabilities': component_data['vulnerability_data']['vulnerabilities']
            },
            'security_metrics': {
                'cvss_max_score': max([v['cvss_score'] for v in component_data['vulnerability_data']['vulnerabilities']], default=0.0),
                'vulnerability_count': len(component_data['vulnerability_data']['vulnerabilities']),
                'exploit_confidence': exploit_prediction['confidence_score']
            },
            'recommendations': generate_recommendations(
                component,
                patterns,
                exploit_prediction
            )
        }
        
        results['components'].append(component_analysis)
        
        # Track critical components
        if component_analysis['threat_analysis']['risk_score'] > 0.7:
            results['critical_components'].append({
                'name': component['name'],
                'version': component['version'],
                'risk_score': component_analysis['threat_analysis']['risk_score'],
                'critical_vulnerabilities': [
                    v for v in component_data['vulnerability_data']['vulnerabilities']
                    if v['severity'] == 'CRITICAL'
                ]
            })
    
    # Calculate overall risk score
    results['overall_risk_score'] = calculate_overall_risk(results['components'])
    
    # Generate security recommendations
    results['security_recommendations'] = prioritize_recommendations(
        [rec for comp in results['components'] for rec in comp['recommendations']]
    )
    
    return results

def enrich_component_data(component):
    """Enrich component data with vulnerability information"""
    # This would typically fetch data from NVD, OSV, etc.
    # Using example data for demonstration
    
    if component['name'] == 'log4j-core' and component['version'] == '2.14.1':
        return {
            'name': component['name'],
            'version': component['version'],
            'description': 'Apache Log4j 2 Core',
            'vulnerability_data': {
                'vulnerabilities': [
                    {
                        'cve_id': 'CVE-2021-44228',
                        'severity': 'CRITICAL',
                        'cvss_score': 10.0,
                        'cvss_vector': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H',
                        'description': 'Remote code execution vulnerability in Log4j',
                        'published_date': '2021-12-10',
                        'attack_vector': 'remote',
                        'has_exploit': True,
                        'exploit_maturity': 'high'
                    }
                ]
            }
        }
    elif component['name'] == 'guava' and component['version'] == '30.0-jre':
        return {
            'name': component['name'],
            'version': component['version'],
            'description': 'Google Guava Core Libraries for Java',
            'vulnerability_data': {
                'vulnerabilities': [
                    {
                        'cve_id': 'CVE-2020-8908',
                        'severity': 'MEDIUM',
                        'cvss_score': 5.5,
                        'cvss_vector': 'CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:N',
                        'description': 'Information disclosure in Guava Temporary Directory Creation',
                        'published_date': '2020-12-08',
                        'attack_vector': 'local',
                        'has_exploit': False,
                        'exploit_maturity': 'low'
                    }
                ]
            }
        }
    
    return {
        'name': component['name'],
        'version': component['version'],
        'description': 'Unknown component',
        'vulnerability_data': {
            'vulnerabilities': []
        }
    }

def generate_recommendations(component, patterns, exploit_prediction):
    """Generate security recommendations for a component"""
    recommendations = []
    
    # Version update recommendations
    if patterns['risk_level'] == 'high':
        recommendations.append({
            'type': 'version_update',
            'priority': 'critical',
            'description': f"Update {component['name']} to latest secure version",
            'details': 'Critical vulnerabilities detected'
        })
    
    # Security control recommendations
    if exploit_prediction['exploit_probability'] > 0.7:
        recommendations.append({
            'type': 'security_control',
            'priority': 'high',
            'description': 'Implement additional security controls',
            'details': exploit_prediction['explanation']['key_factors']
        })
    
    # Architecture recommendations
    if patterns.get('code_analysis', {}).get('risk_level') == 'high':
        recommendations.append({
            'type': 'architecture',
            'priority': 'medium',
            'description': 'Consider architectural changes to reduce risk exposure',
            'details': patterns['code_analysis'].get('recommendations', [])
        })
    
    return recommendations

def calculate_overall_risk(components):
    """Calculate overall risk score"""
    if not components:
        return 0.0
    
    # Weight factors
    weights = {
        'risk_score': 0.3,
        'exploit_probability': 0.3,
        'cvss_max_score': 0.2,
        'vulnerability_count': 0.2
    }
    
    total_score = 0.0
    for comp in components:
        component_score = (
            comp['threat_analysis']['risk_score'] * weights['risk_score'] +
            comp['threat_analysis']['exploit_probability'] * weights['exploit_probability'] +
            (comp['security_metrics']['cvss_max_score'] / 10.0) * weights['cvss_max_score'] +
            min(comp['security_metrics']['vulnerability_count'] / 5.0, 1.0) * weights['vulnerability_count']
        )
        total_score = max(total_score, component_score)
    
    return total_score

def prioritize_recommendations(recommendations):
    """Prioritize and deduplicate recommendations"""
    priority_order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3}
    
    # Sort by priority
    sorted_recs = sorted(
        recommendations,
        key=lambda x: priority_order.get(x['priority'], 999)
    )
    
    # Deduplicate while preserving order
    seen = set()
    unique_recs = []
    for rec in sorted_recs:
        key = (rec['type'], rec['description'])
        if key not in seen:
            seen.add(key)
            unique_recs.append(rec)
    
    return unique_recs

def main():
    """Run analysis on test SBOM"""
    results = analyze_sbom(test_sbom)
    
    print("\n=== Analysis Results ===")
    print(f"\nOverall Risk Score: {results['overall_risk_score']:.2f}")
    
    print("\nCritical Components:")
    for comp in results['critical_components']:
        print(f"\n- {comp['name']} {comp['version']}")
        print(f"  Risk Score: {comp['risk_score']:.2f}")
        print("  Critical Vulnerabilities:")
        for vuln in comp['critical_vulnerabilities']:
            print(f"    - {vuln['cve_id']}: {vuln['description']}")
    
    print("\nDetailed Component Analysis:")
    for comp in results['components']:
        print(f"\n{comp['name']} {comp['version']}:")
        print(f"  Risk Score: {comp['threat_analysis']['risk_score']:.2f}")
        print(f"  Exploit Probability: {comp['threat_analysis']['exploit_probability']:.2f}")
        print(f"  Confidence: {comp['security_metrics']['exploit_confidence']:.2f}")
        print("  Vulnerabilities:")
        for vuln in comp['threat_analysis']['vulnerabilities']:
            print(f"    - {vuln['cve_id']} ({vuln['severity']})")
    
    print("\nSecurity Recommendations:")
    for i, rec in enumerate(results['security_recommendations'], 1):
        print(f"\n{i}. [{rec['priority'].upper()}] {rec['description']}")
        if 'details' in rec:
            if isinstance(rec['details'], list):
                for detail in rec['details']:
                    print(f"   - {detail}")
            else:
                print(f"   {rec['details']}")

if __name__ == '__main__':
    main()