# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.sbomai_ai.protos import sbomai_ai_pb2 as src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/sbomai_ai/protos/sbomai_ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SbomaiAiServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSbom = channel.unary_unary(
                '/sbomai_ai.SbomaiAiService/AnalyzeSbom',
                request_serializer=src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2.AnalyzeSbomRequest.SerializeToString,
                response_deserializer=src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2.AnalyzeSbomResponse.FromString,
                _registered_method=True)
        self.StreamAnalysis = channel.unary_stream(
                '/sbomai_ai.SbomaiAiService/StreamAnalysis',
                request_serializer=src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2.StreamAnalysisRequest.SerializeToString,
                response_deserializer=src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2.StreamAnalysisResponse.FromString,
                _registered_method=True)


class SbomaiAiServiceServicer(object):
    """Service definition
    """

    def AnalyzeSbom(self, request, context):
        """Analyze SBOM document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAnalysis(self, request, context):
        """Stream analysis results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SbomaiAiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSbom': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSbom,
                    request_deserializer=src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2.AnalyzeSbomRequest.FromString,
                    response_serializer=src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2.AnalyzeSbomResponse.SerializeToString,
            ),
            'StreamAnalysis': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAnalysis,
                    request_deserializer=src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2.StreamAnalysisRequest.FromString,
                    response_serializer=src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2.StreamAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sbomai_ai.SbomaiAiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sbomai_ai.SbomaiAiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SbomaiAiService(object):
    """Service definition
    """

    @staticmethod
    def AnalyzeSbom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sbomai_ai.SbomaiAiService/AnalyzeSbom',
            src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2.AnalyzeSbomRequest.SerializeToString,
            src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2.AnalyzeSbomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sbomai_ai.SbomaiAiService/StreamAnalysis',
            src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2.StreamAnalysisRequest.SerializeToString,
            src_dot_sbomai__ai_dot_protos_dot_sbomai__ai__pb2.StreamAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
